name: AI Code Review

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ai_review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get code diff
        run: |
          if [ "${GITHUB_EVENT_NAME}" = "pull_request" ]; then
            git fetch origin main
            git diff origin/main...HEAD > diff.txt
          else
            git diff HEAD^ HEAD > diff.txt
          fi

      - name: Debug input files
        run: |
          echo "=== RULES FILE CONTENT ==="
          cat .github/workflows/review_rules.md || echo "❌ review_rules.md NOT FOUND!"
          echo "=== DIFF FILE CONTENT ==="
          cat diff.txt || echo "❌ diff.txt is empty!"

          if [ ! -s .github/workflows/review_rules.md ]; then
            echo "❌ ERROR: Rules file is missing or empty!"
            exit 1
          fi
          if [ ! -s diff.txt ]; then
            echo "❌ ERROR: No code changes detected!"
            exit 1
          fi

      - name: Run AI review
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          RULES=$(cat .github/workflows/review_rules.md | jq -Rs .)
          DIFF_CONTENT=$(cat diff.txt | jq -Rs .)

          PROMPT=$(jq -n --arg rules "$RULES" --arg diff "$DIFF_CONTENT" '$rules + "\n" + $diff')

          echo "=== Sending prompt to OpenAI ==="
          echo "$PROMPT"

          REQUEST_BODY=$(jq -n --arg system "You are a senior software engineer reviewing code." --arg user "$PROMPT" '{
            model: "gpt-4o-mini",
            messages: [
              {role: "system", content: $system},
              {role: "user", content: $user}
            ]
          }')

          RESPONSE_RAW=$(curl -s -w "\nHTTP_STATUS:%{http_code}\n" https://api.openai.com/v1/chat/completions \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -d "$REQUEST_BODY")

          echo "=== RAW RESPONSE FROM OPENAI ==="
          echo "$RESPONSE_RAW"

          HTTP_STATUS=$(echo "$RESPONSE_RAW" | grep HTTP_STATUS | cut -d: -f2)
          if [ "$HTTP_STATUS" != "200" ]; then
            echo "❌ ERROR: OpenAI API request failed with status $HTTP_STATUS"
            exit 1
          fi

          RESPONSE=$(echo "$RESPONSE_RAW" | grep -v HTTP_STATUS | jq -r '.choices[0].message.content')
          if [ "$RESPONSE" == "null" ] || [ -z "$RESPONSE" ]; then
            echo "❌ ERROR: No response from OpenAI!"
            exit 1
          fi

          echo "$RESPONSE" > review_result.txt


      - name: Show AI review result in logs
        run: cat review_result.txt

      - name: Post comment to PR (if PR)
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: review_result.txt

            - name: Send review result to Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          REVIEW=$(cat review_result.txt)
          PAYLOAD=$(jq -n --arg text "$REVIEW" '{text: $text}')
          curl -X POST -H 'Content-type: application/json' --data "$PAYLOAD" $SLACK_WEBHOOK_URL

